version = 3
final_space = true

[transient_prompt]
  template = ' ❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}cyan{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = false

  [[blocks.segments]]
    template = ' {{ .HostName }}'
    foreground = 'black'
    leading_powerline_symbol = '█'
    powerline_symbol = ''
    background = 'cyan'
    type = 'session'
    style = 'powerline'

  [[blocks.segments]]
    background = 'darkGray'
    foreground = 'default'
    type = 'os'
    style = 'powerline'
    powerline_symbol = ''

  [[blocks.segments]]
    foreground = 'lightWhite'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      home_icon = '󱂵 '
      style = 'letter'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = ' {{ .CurrentDate | date .Format }} '
    foreground = 'default'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      time_format = '15:04'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ' '
    foreground = 'black'
    background = 'yellow'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      style = 'round'
      threshold = 500

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ' '
    template = '{{ .UpstreamIcon }} {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
    foreground = 'black'
    background = 'white'
    type = 'git'
    style = 'diamond'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}', '{{ if gt .Ahead 0 }}magenta{{ end }}', '{{ if gt .Behind 0 }}magenta{{ end }}']

    [blocks.segments.properties]
      fetch_status = true
      fetch_upstream_icon = true
      source = 'cli'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

[[blocks.segments]]
    foreground = 'lightWhite'
    type = 'session'
    style = 'plain'
    template = ' {{ if .SSHSession }} {{ end }} {{ .UserName }} '

  [[blocks.segments]]
    template = ''
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}lightWhite{{end}}']
